implementing hashtags per UAX31 standard
deltachat/message-parser pull request #40
Opened 2023-08-09 12:29 UTC by farooqkz

Hello. This is a draft. I am stuck with Rust stuff :)

I need some hints. Like how to pass the sets to `hashtag` and advice on implementing `From<PropertiesError> for CustomError`. Furthermore, I've upgraded the rust toolchain to `1.71.0` because `icu_properties` requires it.

2023-08-09 16:45 UTC, Simon-Laux commented on src/parser/parse_from_text/text_elements.rs
> +    };
if this is loaded every time the function is run then it is a waste of time and energy, better use something like https://docs.rs/lazy_static/latest/lazy_static/

2023-08-09 16:53 UTC, Simon-Laux commented on src/parser/parse_from_text/text_elements.rs
> +        '#' | '﹟' | '＃'
even if the small and full width number signs are in the spec, I don't think it makes sense to actually implement them into our spec (spec.md):
- A. if you search for tags, the tags would be different even if they have the same text, because the hashtag character is a different one. Adding extra logic to mitigate this would only complicate things without any real benefit.
- B. to my knowledge the alternative signs are not easily type-able and most people don't even know that they exist.
- C. other programs like mastodon do not support the alternative signs either

2023-08-09 16:56 UTC, Simon-Laux commented
`icu_properties` seems big, I would prefer if we could live without it. Like there is a difference between an emoji regex that checks for each emoji and one that checks for unicode ranges instead. Like if code point is in this range instead of comparing with all code points of that range - if possible that would be faster, less code and less binary size.

2023-08-10 11:04 UTC, farooqkz commented on src/parser/parse_from_text/text_elements.rs
> +        '#' | '﹟' | '＃'
okay agreed. Using the first hashtag only.

2023-08-10 11:48 UTC, farooqkz commented
> `icu_properties` seems big, I would prefer if we could live without it. Like there is a difference between an emoji regex that checks for each emoji and one that checks for unicode ranges instead. Like if code point is in this range instead of comparing with all code points of that range - if possible that would be faster, less code and less binary size.

It turns out we have to extract from here:

https://www.unicode.org/Public/14.0.0/ucdxml/

2023-08-10 17:26 UTC, Simon-Laux commented
allowing only a subset and expanding later is better that allowing more and restricting later. It does not have to be 100% perfect on the first try

2023-08-13 11:40 UTC, farooqkz commented
> `icu_properties` seems big, I would prefer if we could live without it. Like there is a difference between an emoji regex that checks for each emoji and one that checks for unicode ranges instead. Like if code point is in this range instead of comparing with all code points of that range - if possible that would be faster, less code and less binary size.

Are you sure it's big? The binary size is only about 100 KB larger.

2023-08-13 13:18 UTC, farooqkz commented
Okay we've got two ways:

 - Create our own hashtag content character detector crate which I guess will be about 20-30 KB binary size and use it in this crate.
 - Use `icu_properties` and make it optional. With this option, the hashtag detection will be done exactly as UAX31 has specified. Without it, we consider any non whitespace character a content character but ~100KB less binary size.

2023-08-14 09:24 UTC, farooqkz commented
Okay. My new estimate is that if we implement our own solution, it'll be only about 10KB additional binary size.

2023-08-14 10:42 UTC, farooqkz commented
> Okay. My new estimate is that if we implement our own solution, it'll be only about 10KB additional binary size.

Okay I was wrong. See my latest commit. It's about 36KB :)

Also @Simon-Laux, for some reason I can't tell, the tests are not passing :/

2023-08-14 18:36 UTC, Simon-Laux commented
> Also @Simon-Laux, for some reason I can't tell, the tests are not passing :/

if you read the clip error it complains being run from a branch on your fork.

2023-08-14 18:49 UTC, Simon-Laux requested changes

2023-08-14 18:49 UTC, Simon-Laux commented on src/parser/parse_from_text/hashtag_content_char_ranges.rs
> +    [0x23, 0x23],
is there a difference between using a array with 2 elements and a tuple with 2 elements?

2023-08-14 18:49 UTC, Simon-Laux commented on src/parser/parse_from_text/text_elements.rs
> +                    || (code >= range1[0] && code <= range1[1])
could you document why this checks 2 ranges at once?

2023-08-14 18:49 UTC, Simon-Laux commented on src/parser/parse_from_text/text_elements.rs
> +        match index {
move this logic in a separate function and file so we can easily add a unit test that tests it for all combinations.

2023-08-15 09:15 UTC, farooqkz commented on src/parser/parse_from_text/hashtag_content_char_ranges.rs
> +    [0x23, 0x23],
What is advantage of using a tuple?

2023-08-15 09:20 UTC, Simon-Laux commented on src/parser/parse_from_text/hashtag_content_char_ranges.rs
> +    [0x23, 0x23],
no accessing via `[index]` which could panic (not in our case but still might generate code for panic). I'm wondering wether we can skip that with tuple

2023-08-15 10:14 UTC, farooqkz commented on src/parser/parse_from_text/hashtag_content_char_ranges.rs
> +    [0x23, 0x23],
I've used `RangeInclusive` which is the best option.

2023-08-15 10:45 UTC, farooqkz commented
Okay. In these final commits:

 - I've moved the function for finding range to its own file alongside with the ranges themselves.
 - I've used `RangeInclusive` and its `contains` method instead of `[u32; 2]`.
 - A new enum has been defined as the result of the find range function.
 
But still the tests for German umlauts fail. Even though the left and right of the assertions seem to be equal:

```
---- text_to_ast::text_only::german_umlaut_hashtag stdout ----
thread 'text_to_ast::text_only::german_umlaut_hashtag' panicked at 'assertion failed: `(left != right)`
  left: `[Tag("#bücher"), Text(" "), Tag("#Ängste")]`,
 right: `[Tag("#bücher"), Text(" "), Tag("#Ängste")]`', tests/text_to_ast/text_only.rs:114:5
```

2023-08-15 11:15 UTC, Simon-Laux requested changes
I still want a unit test that checks all ranges, and more example tests with different "real" use cases. But other than that the code looks good I'd say (didn't test nor benchmark it yet)

2023-08-15 18:11 UTC, farooqkz commented
> I still want a unit test that checks all ranges, and more example tests with different "real" use cases. But other than that the code looks good I'd say (didn't test nor benchmark it yet)

So you want test cases for the range function separately? I will add more real use case tests. But I also need hint from you why these tests fail :/

2023-08-16 12:41 UTC, Simon-Laux commented
> So you want test cases for the range function separately? I will add more real use case tests. But I also need hint from you why these tests fail :/

yes, you can also test for the german umlaute there: `ö`, `ä`, `ü` and the sharp s: `ß`

2023-08-23 08:40 UTC, farooqkz commented
@Simon-Laux  Ready to merge :D

2023-08-24 11:59 UTC, Simon-Laux approved these changes

2023-08-24 15:35 UTC, merged