simon/i26 emoji helper functions
deltachat/message-parser pull request #56
Opened 2023-11-16 11:24 UTC by Simon-Laux

- add emoji parsing and a few helper functions
- update changelog and readme
- wasm api demo and readme
- add two failing cases that I found while making the web demo

closes #26

TODO:
- [ ] fix failing test cases

2024-03-05 11:20 UTC, Simon-Laux commented
What is this?

Basically provides helper functions for emoji parsing, which allow us:
- to replace the regex in desktop (and maybe android) for detecting if an emoji message should be displayed bigger because it contains only a few emojis:(sometimes also called "jumbomoi"?)
   - iOS already has good system unicode emoji detection in swift
- and the pr is a pre-requisite for other tasks such as
  -  a mode where [emojis are parsed into a dedicated element](https://github.com/deltachat/message-parser/pull/56#https://github.com/deltachat/message-parser/issues/58), useful for systems where unicode emoji font rendering is buggy (deltatouch, maybe also older android versions and kaiOS);
  - or another usecase could be for core to know what an emoji exactly is for example to allow emoji text avatars but not other avatars, which was a recent topic of a meeting, where bjoern and others proposed a default avatar.

2024-05-06 13:21 UTC, farooqkz requested changes

2024-05-06 13:21 UTC, farooqkz commented on src/parser/is_emoji.rs
> +    matches!(c,
I think it might be better to use `is_in_one_of_ranges` as introduced by me which uses binary search over a sorted slice of ranges(one number can be represented as a range of an integer)

2024-05-06 13:24 UTC, farooqkz commented on src/parser/is_emoji.rs
> +            many1(satisfy(|c| matches!(c, '\u{e0061}'..='\u{e007a}'))),
So I guess a combination of `many1` and `satisfy` is used instead of `take_while1` to recognize characters instead of a string. right?

2024-05-06 14:11 UTC, farooqkz commented on src/parser/is_emoji.rs
> +    matches!(c,
I don't think the possible speedup thing is worth it.

2024-05-07 00:27 UTC, Simon-Laux commented on src/parser/is_emoji.rs
> +    matches!(c,
if benchmarking and profiling ever show that it is slow we can keep that in mind, good idea, but I would wait until it is really a problem, also because this function is not used in big messages yet anyway.
So good idea for later 👍

2024-05-07 00:29 UTC, Simon-Laux commented on src/parser/is_emoji.rs
> +            many1(satisfy(|c| matches!(c, '\u{e0061}'..='\u{e007a}'))),
yes probably (though it is too long ago, so I don't remember every detail of the pr)

2024-05-07 11:07 UTC, merged