Add Labelled hashtag
deltachat/message-parser pull request #69
Opened 2024-05-09 13:18 UTC by farooqkz

2024-05-10 23:46 UTC, Simon-Laux commented on src/parser/mod.rs
> +    },
this is also a markdown element I would put it right before or after the Labled link.
Also use `Vec<Element>` instead of box, there can be multiple elements, the label can be a sentence with a bold word for example.

2024-05-10 23:48 UTC, Simon-Laux commented
don't forget to add the specification for the new element to [`spec.md`](https://github.com/deltachat/message-parser/blob/master/spec.md). It will be desktop- and markdown-set element.

2024-05-29 08:31 UTC, farooqkz commented
> don't forget to add the specification for the new element to [`spec.md`](https://github.com/deltachat/message-parser/blob/master/spec.md). It will be desktop- and markdown-set element.

Do we need labelled hashtags in desktop and markdown sets, too?

2024-05-29 12:14 UTC, Simon-Laux commented on spec.md
> +  - [Labeled hashtags: `[Tag][#tag]`](#labeled-tags)
do we also want to have this in the desktop set?

2024-05-29 12:15 UTC, Simon-Laux commented on spec.md
> +
please also make an example and spec to define how it looks like:
```
[Label](#tag)
```

2024-05-29 12:28 UTC, Simon-Laux commented on src/main.rs
seems unrelated, I guess we should turn this into a full cli-app at some point where you can select the mode via argument. (maybe with the clap library)

2024-05-29 12:34 UTC, Simon-Laux commented on src/parser/parse_from_text/text_elements.rs
> +        Ok((i, elm))
the fabled tag should only be in the markdown set and maybe also in the desktop set, but not in the text set.
rule of thumb: Things in the text set are kept at the original, just linkified, but text is still the same

2024-05-29 12:36 UTC, Simon-Laux requested changes
should only be part of markdown and (maybe, if you think it makes sense) desktop set, not the text set

2024-05-29 13:23 UTC, farooqkz commented on src/parser/parse_from_text/text_elements.rs
> +        Ok((i, elm))
You sure? hashtag is already in text elements.

2024-05-29 13:29 UTC, Simon-Laux commented on src/parser/parse_from_text/text_elements.rs
> +        Ok((i, elm))
yes, labeled link and labeled hashtag both modify the text, while text elements only make the text clickable

2024-05-29 13:34 UTC, Simon-Laux commented on src/parser/parse_from_text/text_elements.rs
> +    let elements: Vec<Element> = parse_only_text(label);
If we merge #74 first, then we can allow markdown formatting for the thing in markdown mode and in desktop mode this should just allow text. So we don't repeat #59 (there should no be any clickable elements in the label, otherwise it's confusing/not-good-defined what happens)

2025-04-08 08:19 UTC, farooqkz commented
Given that MP is used only on Desktop, I don't think we can use this only for Desktop(it'll lead to inconsistency). And I'm not motivated to add it to MP and leave it without use. If you agree, I will close this.

2025-04-08 09:19 UTC, Simon-Laux commented
given that the desktop set is no longer used by desktop, we could just add it to the markdown set, which is opt in experimental anyway.

2025-04-08 10:13 UTC, r10s commented
i think, i mentioned that at some point in one to one: while _labeled links_ are already questionable in messengers,  _labeled hashtags_ look very  theoretical and nerdy at best.  potentially even like an anti-feature, caussing troubles, as introducing a not really used code path, known only by some folk might getting ideas how to abuse that, finding bugs  to abuse etc.

do any other messengers have this kind of feature? why should any normal user want to use labeled links? i do not know about them even in social media,  where hashtags are much more of a thing.

2025-04-08 11:12 UTC, Simon-Laux commented
> known only by some folk might getting ideas how to abuse that, finding bugs to abuse etc.

starting a search for a hashtag is not something you can really abuse.

> "Do you want to search for hashtage #bob"

as if you would need warnings on starting a local search that changes nothing in your db.

---

Labeled hashtags are just an idea at this point. idea came from the bug that labeled links that have a single hashtag as target. So an alternative solution to the problem that the syntax doesn't make sense: `[label](#fragment)`. The 2 solution ideas were:
- use the syntax to have labeled hashtags
- display the whole thing as text because the link is not valid

reasoning of that alternative idea:
> To have labled hashtags, meaning like labled links just for hashtags
```[click here to see everything you can do to contribute to our cause](#contribute)```
> Though a disadvantage to labeled hashtags could be that the the messages with those links would also appear int eh hashtag search results, as the hashtag is still part of the message and core does not do any special parsing when searching for them.

But in my mind we could also just go for the normal solution (don't parse the text if link is just a fragment/anchor) and close this.

2025-04-08 11:36 UTC, r10s commented
> starting a search for a hashtag is not something you can really abuse.

sure, if everything is working perfectly and there are no bugs. but if this is not the case, there is a rarely/never used feature waiting for someone to find out things ...

> But in my mind we could also just go for the normal solution (don't parse the text if link is just a fragment/anchor) and close this.

makes sense, +1 for closing this

2025-04-08 11:51 UTC, closed without merging